<?php
$id = '';
if (!empty($this->zoneconfig['conf']['id']))
    $id = ' id="' .$this->zoneconfig['conf']['id'] . '"';
?>
<div class="modal-content" <?= $id; ?> data-melisKey="<?= $this->melisKey; ?>">
    <div class="modal-body padding-none">
        <div class="wizard">
            <div class="widget widget-tabs widget-tabs-double widget-tabs-responsive margin-none border-none">
                <div class="widget-head">
                    <ul class="nav nav-tabs">
                        <li class="active">
                            <?php
                            if(!empty($this->albumId)) {
                                $title = $this->translate('Update Album');
                                $icon = 'glyphicons edit';
                            }else {
                                $title = $this->translate('New Album');
                                $icon = 'glyphicons plus';
                            }
                            ?>
                            <a href="#<?php echo $this->zoneconfig['conf']['id'] ?>" class="<?= $icon; ?>" data-toggle="tab" aria-expanded="true"><i></i>
                                <?= $title; ?>
                            </a>
                        </li>
                    </ul>
                </div>
                <div class="widget-body innerAll inner-2x">
                    <div class="tab-content">
                        <div class="tab-pane active" id="<?= $id ?>">
                            <?= $this->form; ?>
                        </div>
                        <br>
                        <br>
                    </div>
                    <div align="right">
                        <button type="button" data-dismiss="modal" class="btn btn-danger pull-left">Cancel</button>
                        <button type="button" class="btn btn-success" id="btn-save-album">Save</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>